name: Deploy Static Website to S3

on:
  push:
    branches:
    - main
  workflow_dispatch:
    branches:
    - main

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: aws-actions/configure-aws-credentials@v1
        name: Configure AWS Credentials
        with:
          aws-s3-bucket: ${{ secrets.S3_BUCKET }}
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Upload file to S3 bucket
        run: aws s3 cp index.html s3://${{ secrets.S3_BUCKET }}
